version: "3.8"

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181" # Expose Zookeeper on port 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # Expose Kafka on port 9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Reference Zookeeper container
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # Advertise Kafka on localhost
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # Kafka listens on all interfaces
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1" # Single replication factor for dev
